### ISSUE TITLE
Full screen weather extended freezing and exiting Rise player on FireOS

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/content-templates#100] opened 2022-09-15 20:55 UTC
https://www.risevision.com/template-details/full-screen-video-weather-extended  

This template is crashing on FireOS. It freezes the display at times and exits the player to the home menu. 

I have been able to replicate this.

**Comment by santiagonoguez** [comment] 2022-12-05 18:17
@mmeiers should this template be updated to use rise-video ? Thanks !

**Comment by santiagonoguez** [comment] 2022-12-28 17:20
@cameronreidrisevision to confirm, you replicated on a Firestick 4K Max ? How long did it take the error to occur ?

I'm trying to replicate in mine. Thanks !

**Comment by robb-price** [comment] 2022-12-29 13:52
@santiagonoguez I believe it was pretty quick to replicate. I'm testing it on mine here as well, I will let you know if I can replicate too.

**Comment by santiagonoguez** [comment] 2022-12-29 14:04
@robb-price thanks ! I left mine runnning since yesterday, and it's still on. Maybe if I combine this template with others it will fail. I'll test that next.

**Comment by santiagonoguez** [comment] 2022-12-29 14:50
Finally could reproduce, when I combine this template on a schedule with another presentation with a video, it starts failing. I see lots of MediaCodec and GL errors similar to the ones we saw before with Firestick and Video. At that point we did a fix for video components as Amazon never fixed their internal workings.

So, for this case, I see we could do one of the following options:
- Creative team could update this to use rise-video instead of video tag, as rise-video was fixed at some point. But I believe @mmeiers once commented this change was not straightforward.
- As part of the next epic we could prevent this template from running on Firestick, or at least prevent the background video from running on Firestick.

Any thoughts ? @ezequielc @tejohnso @mmeiers

**Comment by robb-price** [comment] 2023-01-05 19:50
@mmeiers @ezequielc @santiagonoguez It appears to happen with this presentation as well: https://www.risevision.com/template-details/auto-update-famous-athletes

I updated the bug details above.

**Comment by santiagonoguez** [comment] 2023-01-24 17:24
@mmeiers thanks for the analysis. After testing low quality videos on some of these devices, I agree that downgrading videos is not going to help much.

I'm currently working with the flag that signals poor performance. Once it's available I'll let you know.

FYI @tejohnso @stulees

**Comment by mmeiers** [comment] 2023-02-13 14:19
@robb-price Can you check the weather template on your firestick. It should still be showing videos but more compressed versions. Can you take a picture.

**Comment by mmeiers** [comment] 2023-02-14 14:15
Robb confirmed. Closing defect.

**Closed by mmeiers** 2023-02-14 14:15 UTC
